[[regions]]
  id="cn470_1"
  description="CN470 (channels 8-15)"
  common_name="CN470"

  [regions.gateway]

    [regions.gateway.backend]
      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        topic_prefix="cn470_1"
        server="tcp://localhost:1883"

    [[regions.gateway.channels]]
      frequency=471900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=472100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=472300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=472500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=472700000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=472900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=473100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=473300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

  [regions.network]
    rx1_delay=1
    rx2_dr=0
    rx2_frequency=505300000
    min_dr=0
    max_dr=5
    enabled_uplink_channels=[8, 9, 10, 11, 12, 13, 14, 15]

    [regions.network.class_b]
      ping_slot_dr=0
