[[regions]]
  id="cn470_7"
  description="CN470 (channels 56-63)"
  common_name="CN470"

  [regions.gateway]

    [regions.gateway.backend]
      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        topic_prefix="cn470_7"
        server="tcp://localhost:1883"

    [[regions.gateway.channels]]
      frequency=481500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=481700000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=481900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=482100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=482300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=482500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=482700000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=482900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

  [regions.network]
    rx1_delay=1
    rx2_dr=0
    rx2_frequency=505300000
    min_dr=0
    max_dr=5
    enabled_uplink_channels=[56, 57, 58, 59, 60, 61, 62, 63]

    [regions.network.class_b]
      ping_slot_dr=0
