[[regions]]
  id="cn470_6"
  description="CN470 (channels 48-55)"
  common_name="CN470"

  [regions.gateway]

    [regions.gateway.backend]
      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        topic_prefix="cn470_6"
        server="tcp://localhost:1883"

    [[regions.gateway.channels]]
      frequency=479900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=480100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=480300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=480500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=480700000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=480900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=481100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=481300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

  [regions.network]
    rx1_delay=1
    rx2_dr=0
    rx2_frequency=505300000
    min_dr=0
    max_dr=5
    enabled_uplink_channels=[48, 49, 50, 51, 52, 53, 54, 55]

    [regions.network.class_b]
      ping_slot_dr=0
