[general]
log_level=4

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@localhost/chirpstack_ns?sslmode=disable"

[network_server]
net_id="000000"

  [network_server.band]
  name="AU_915_928"

  [network_server.network_settings]
  enabled_uplink_channels=[56, 57, 58, 59, 60, 61, 62, 63]

