[general]
log_level=4
log_to_syslog=true

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@localhost/chirpstack_ns?sslmode=disable"

[network_server]
net_id="000000"

  [network_server.band]
  name="US915"

  [network_server.network_settings]
  enabled_uplink_channels=[16, 17, 18, 19, 20, 21, 22, 23]
