[general]
log_level=4

[postgresql]
dsn="postgres://loraserver_ns:loraserver_ns@localhost/loraserver_ns?sslmode=disable"

[network_server]
net_id="000000"

  [network_server.band]
  name="US_902_928"
  enabled_uplink_channels=[40, 41, 42, 43, 44, 45, 46, 47]

